#!/bin/bash

DOTFILES=$(realpath "$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/..")
source $DOTFILES/scripts/symlinks.sh
source $DOTFILES/scripts/log.sh

powershell -noprofile Set-ExecutionPolicy RemoteSigned

profilePath=$(powershell -noprofile \$profile)

etrace "Moving profile to old backup"
mv -f $profilePath $(windowsPath "$DOTFILES/old/$(basename $profilePath)-$(date +%s%N)")
etrace "Writing the new profile"
echo "powershell -noprofile -nologo -NoExit -File $(windowsPath "$DOTFILES/windows/.profile.ps1")" > "$profilePath"

einfo "Creating windows symlinks"
replace $DOTFILES windows
