#!/bin/bash

DOTFILES=$(realpath "$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")
source $DOTFILES/scripts/log.sh

if [[ "$HOME" == "/home/codespace" ]]; then
    eerror "Codespaces do not have installation process."
    exit
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    estart "Linux dotfile installation."
    $DOTFILES/linux/install
elif [[ "$OSTYPE" == "darwin"* ]]; then
    estart "Mac OSX dotfile installation."
    $DOTFILES/darwin/install
elif [[ "$OSTYPE" == "msys"* ]]; then
    estart "Windows dotfile installation"
    $DOTFILES/windows/install
else
    eerror "Unknow system: $OSTYPE. Installation not started."
    exit
fi

eend "Installation finished."

$DOTFILES/setup
