#!/bin/bash

DOTFILES=$(realpath "$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")
source $DOTFILES/scripts/log.sh

if [[ "$HOME" == "/home/codespace" ]]; then
    estart "Codespaces configuration."
    $DOTFILES/codespace/setup
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    estart "Linux dotfile configuration."
    $DOTFILES/linux/setup
elif [[ "$OSTYPE" == "darwin"* ]]; then
    estart "Mac OSX dotfile configuration."
    $DOTFILES/darwin/setup
elif [[ "$OSTYPE" == "msys"* ]]; then
    estart "Windows dotfile configuration"
    $DOTFILES/windows/setup
else
    eerror "Unknow system. Configuration not started."
    exit
fi

eend "Configuration finished. Restart the system to make sure all configurantions are done"
