#!/bin/bash

DOTFILES=$(realpath "$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/..")
source $DOTFILES/scripts/log.sh

# Install binutils
if ! command -v ld &>/dev/null; then
    einfo "Installing binutils"

    sudo apt install binutils -y
else
    ewarn "binutils already installed"
fi

# Install gcc
if ! command -v gcc &>/dev/null; then
    einfo "Installing gcc"

    sudo apt install gcc -y
else
    ewarn "gcc already installed"
fi

# Intall make
if ! command -v make &>/dev/null; then
    einfo "Installing make"

    sudo apt install make -y
else
    ewarn "make already installed"
fi

# Install zsh
if ! command -v zsh &>/dev/null; then
    einfo "Installing zsh"

    sudo apt install zsh -y
else
    ewarn "zsh already installed"
fi

# Install Oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    einfo "Installing oh-my-zsh"

    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
else
    ewarn "oh-my-zsh already installed"
fi

# Install starship
if ! command -v starship &>/dev/null; then
    einfo "Installing starship"

    curl -sS https://starship.rs/install.sh | sh
else
    ewarn "starship already installed"
fi

# Install gvm
if ! command -v gvm &>/dev/null; then
    einfo "Installing gvm"

    sudo apt-get install bison -y
    bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

    source ~/.gvm/scripts/gvm

    gvm install go1.4 -B
    gvm use go1.4
    export GOROOT_BOOTSTRAP=$GOROOT
    gvm install go1.17.13
    gvm use go1.17.13
    export GOROOT_BOOTSTRAP=$GOROOT
    gvm install go1.20
    gvm use go1.20
    export GOROOT_BOOTSTRAP=$GOROOT

    lts=$(curl -s "https://go.dev/VERSION?m=text" | head -n 1)
    gvm install $lts
    gvm use $lts --default
    export GOROOT_BOOTSTRAP=$GOROOT
else
    ewarn "gvm already installed"
fi

# Install docker
if ! command -v docker &>/dev/null; then
    einfo "Installing docker"

    sudo apt-get update
    sudo apt-get install ca-certificates curl -y
    sudo install -m 0755 -d /etc/apt/keyrings -y
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

    sudo groupadd --system docker
    sudo adduser $USER docker
    newgrp docker
    sudo chown root:docker /var/run/docker.sock
    sudo chmod g+w /var/run/docker.sock
else
    ewarn "docker already installed"
fi

# # Prepare fonts folder
# if [ ! -d "$HOME/.fonts" ]; then
#     mkdir -p $HOME/.fonts
# fi

# # Install Fira Code Nerdfonts
# if [[ ! -n $(find "$FONTSFILE" -type f -name "FiraCodeNerdFont*" -print -quit) ]]; then
#     # if find "$HOME/.fonts" -type f -name "FiraCodeNerdFont*" -print -quit &>/dev/null; then
#     curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
#     unzip FiraCode.zip -d Firacode
#     mv Firacode/*.ttf $FONTSFILE/
#     rm -r FiraCode.zip Firacode
# else
#     ewarn "FiraCodeNerdFont already installed"
# fi
