#!/bin/bash

DOTFILES=$(realpath "$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/..")
source $DOTFILES/scripts/log.sh

# Install zsh
if ! command -v zsh &>/dev/null; then
    sudo apt install zsh -y
else
    ewarn "zsh already installed"
fi

# Install Oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
else
    ewarn "oh-my-zsh already installed"
fi

# Prepare fonts folder
if [ ! -d "$HOME/.fonts" ]; then
    mkdir -p $HOME/.fonts
fi

# Install Fira Code Nerdfonts
# if [[ ! -n $(find "$FONTSFILE" -type f -name "FiraCodeNerdFont*" -print -quit) ]]; then
#     # if find "$HOME/.fonts" -type f -name "FiraCodeNerdFont*" -print -quit &>/dev/null; then
#     curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FiraCode.zip
#     unzip FiraCode.zip -d Firacode
#     mv Firacode/*.ttf $FONTSFILE/
#     rm -r FiraCode.zip Firacode
# else
#     ewarn "FiraCodeNerdFont already installed"
# fi
